name: Flutter Build APK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'
          channel: 'stable'
          cache: true

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Get dependencies
        run: flutter pub get

      - name: Clean previous build
        run: flutter clean

      - name: Build Debug APK
        run: flutter build apk --debug --no-tree-shake-icons
        env:
          GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx4g -XX:+HeapDumpOnOutOfMemoryError"'

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: talks-app-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
